### ISSUE TITLE
AciertaEuromillon() ??

### ISSUE THREAD

**Issue by jamkami** [jamkami/ej8#1]
aparecen  métodos que no deben estar ahí(en calcfact)
@alvaromartingarcia @ostua

PD: se agradece la intención de hacernos millonarios.

**Comment by alvaromartingarcia** [comment]
voy a ver el archivo.

**Comment by jamkami** [comment]
https://github.com/jamkami/ej8/blob/f410ddd82f7daf0fe840dc6d5339cca2d9e80963/calcfact.c#L4

**Comment by jamkami** [comment]
Problema resuelto.
